// policy-card.ts: the rule templates of the Policy Card builder
// (/toolkit/policy-card). Each template is one governance rule from the curated
// set: what it states, the effect it has, where it is enforced, the failure
// mode it addresses, the obligations it helps evidence by default and the
// parameters a reader sets. The executable side of each template (the Rego
// module and its tests, the Cedar stub and its tests, the example input and the
// CI hook) is generated by public/toolkit/policy-card-core.js, which reads this
// data from the page's JSON island; tests/policy-card.spec.ts checks that the
// two agree template by template.
//
// This file imports nothing, so scripts/policy-card-samples.mjs can load it
// under `node --experimental-strip-types` to write the committed samples in
// public/templates/policy-cards/.
//
// `{name}` in `statement` and `condition` is replaced with the parameter's
// value. Default obligation ids are stable ids from src/data/frameworks.ts
// (the page fails the build on an unknown id). Mappings are illustrative, not a
// claim of conformity.

export type PolicyEffect = 'deny' | 'allow' | 'require_approval' | 'alert';
export type EnforcementPoint = 'pre_merge' | 'deploy' | 'runtime' | 'periodic';

/** How a parameter is entered and checked.
 * - `token`: one word-like value (letters, digits and . _ : / @ + -).
 * - `tokens`: a comma-separated list of tokens (may be empty only if `optional`).
 * - `int`: a whole number between `min` and `max`.
 * - `decimal`: a number above zero with at most four decimal places.
 * - `path`: a dot path into the input document, snake_case segments.
 * - `operator`: one of the custom-rule comparison operators.
 * - `value`: a token, a number or true/false, read by the operator. */
export type ParamKind = 'token' | 'tokens' | 'int' | 'decimal' | 'path' | 'operator' | 'value';

export interface PolicyCardParam {
  key: string;
  label: string;
  hint: string;
  kind: ParamKind;
  default: string;
  optional?: boolean;
  min?: number;
  max?: number;
}

export interface PolicyCardTemplate {
  /** Kebab-case id; the link state and the sample folder use it. */
  id: string;
  /** The rule, as a short title. */
  title: string;
  /** One line under the title in the picker. */
  summary: string;
  /** The rule in one sentence; `{param}` placeholders are filled in. */
  statement: string;
  /** The condition in plain words; the engine module is authoritative. */
  condition: string;
  effect: PolicyEffect;
  enforcementPoints: readonly EnforcementPoint[];
  failureMode: string;
  /** Defaults for the card fields. */
  ruleId: string;
  cardId: string;
  cardTitle: string;
  appliesTo: readonly string[];
  sourcePolicy: string;
  obligations: readonly string[];
  /** The chapter 05 pattern the rule builds (slug under /patterns). */
  pattern: string;
  params: readonly PolicyCardParam[];
}

/** Operators of the custom rule, with the words the card uses for them. */
export const customOperators = [
  { id: 'missing', label: 'is missing', needsValue: false },
  { id: 'equals', label: 'equals', needsValue: true },
  { id: 'not_equals', label: 'does not equal', needsValue: true },
  { id: 'lt', label: 'is below (number)', needsValue: true },
  { id: 'gt', label: 'is above (number)', needsValue: true },
  { id: 'one_of', label: 'is one of (comma list)', needsValue: true },
  { id: 'not_one_of', label: 'is not one of (comma list)', needsValue: true },
] as const;

export const effectLabels: Readonly<Record<PolicyEffect, string>> = {
  deny: 'deny: block the action',
  require_approval: 'require_approval: hold the action for a human decision',
  alert: 'alert: let the action through and raise an alert',
  allow: 'allow: permit only what matches (everything else is denied)',
};

export const enforcementLabels: Readonly<Record<EnforcementPoint, string>> = {
  pre_merge: 'pre_merge: on every pull request',
  deploy: 'deploy: before a version is deployed or released',
  runtime: 'runtime: at the point of action (gateway or guardrail)',
  periodic: 'periodic: on a schedule, over what is already running',
};

export const policyCardTemplates: readonly PolicyCardTemplate[] = [
  {
    id: 'registered-agents-only',
    title: 'No unregistered agent in production',
    summary:
      'Deny any agent that has no active, owned and in-date entry in the agent registry.',
    statement:
      'No agent runs in {environment} unless it has an active entry in the agent registry, with an owner and an expiry that has not passed.',
    condition:
      'in {environment}, the agent has no registry entry, or its entry is not active, names no owner, has no expiry or has expired',
    effect: 'deny',
    enforcementPoints: ['deploy', 'runtime'],
    failureMode: 'An agent that nobody owns or bounded acts in production (a shadow agent).',
    ruleId: 'agents.registered-only.v1',
    cardId: 'pc-registered-agents-only',
    cardTitle: 'Registered agents only',
    appliesTo: ['agent:*'],
    sourcePolicy: 'ai-policy.yaml#rules/register-before-production',
    obligations: ['AIGE-OBL-EUAIA-ART49-71', 'AIGE-OBL-NIST-AGENTS', 'AIGE-OBL-OWASP-AGENTIC'],
    pattern: 'agent-registry',
    params: [
      {
        key: 'environment',
        label: 'Environment the rule guards',
        hint: 'The value of the environment field in the input, for example production.',
        kind: 'token',
        default: 'production',
      },
    ],
  },
  {
    id: 'eval-score-gate',
    title: 'Eval score at or above a threshold before deploy',
    summary:
      'Fail the merge or the deploy unless the named eval suite scored at or above the minimum for that exact version.',
    statement:
      'A version merges or deploys only if its {suite_id} eval result for that exact version scores at least {min_score}.',
    condition:
      'there is no {suite_id} result for the exact system version, or a result scores below {min_score}',
    effect: 'deny',
    enforcementPoints: ['pre_merge', 'deploy'],
    failureMode:
      'A regressed model version ships because nothing checked the eval result for that exact version.',
    ruleId: 'evals.min-score.v1',
    cardId: 'pc-eval-score-gate',
    cardTitle: 'Eval score gate before deploy',
    appliesTo: ['tier:high', 'tier:critical'],
    sourcePolicy: 'ai-policy.yaml#rules/eval-gate',
    obligations: ['AIGE-OBL-EUAIA-ART15', 'AIGE-OBL-NISTRMF-MEASURE', 'AIGE-OBL-ISO42001-A6'],
    pattern: 'eval-gate-in-ci',
    params: [
      {
        key: 'suite_id',
        label: 'Eval suite id',
        hint: 'The suite_id of the eval results, as in the eval-result schema.',
        kind: 'token',
        default: 'safety-core',
      },
      {
        key: 'min_score',
        label: 'Minimum score',
        hint: 'On the suite\'s own scale, higher is better; at most four decimal places (for example 0.90).',
        kind: 'decimal',
        default: '0.90',
        min: 0.0001,
        max: 1000000,
      },
    ],
  },
  {
    id: 'no-personal-data-external',
    title: 'No personal data sent to an external model',
    summary:
      'Deny any model call that carries a blocked data class to a model hosted outside the organisation.',
    statement:
      'No request that carries {blocked_classes} data is sent to a model hosted outside the organisation; a request without a data classification is treated as carrying it.',
    condition:
      'the model is not hosted internally and the request carries one of {blocked_classes}, or carries no data classification',
    effect: 'deny',
    enforcementPoints: ['runtime'],
    failureMode: 'Personal data leaves the organisation in a prompt to a third-party model.',
    ruleId: 'data.no-personal-data-external.v1',
    cardId: 'pc-no-personal-data-external',
    cardTitle: 'No personal data to external models',
    appliesTo: ['model-gateway:*'],
    sourcePolicy: 'ai-policy.yaml#rules/sanctioned-genai-tools',
    obligations: ['AIGE-OBL-ISO42001-A7', 'AIGE-OBL-ISO42001-A10', 'AIGE-OBL-OWASP-LLM'],
    pattern: 'runtime-guardrail',
    params: [
      {
        key: 'blocked_classes',
        label: 'Blocked data classes',
        hint: 'Comma-separated labels your data classifier puts on a request, for example personal, special_category.',
        kind: 'tokens',
        default: 'personal, special_category',
      },
    ],
  },
  {
    id: 'approval-for-tool',
    title: 'Human approval required for a named tool',
    summary:
      'Hold any agent call to the named tool until a person other than the agent has approved it.',
    statement:
      'An agent calls {tool} ({operations}) only with a recorded approval by a person other than the agent.',
    condition:
      'an agent calls {tool} ({operations}) and the request carries no approval, or the approval was not given or was given by the agent itself',
    effect: 'require_approval',
    enforcementPoints: ['runtime'],
    failureMode: 'An agent takes a consequential action through a tool with no human in the loop.',
    ruleId: 'tools.approval-required.v1',
    cardId: 'pc-approval-for-tool',
    cardTitle: 'Human approval for a named tool',
    appliesTo: ['agent:*'],
    sourcePolicy: 'ai-policy.yaml#rules/agents-bounded-spend',
    obligations: ['AIGE-OBL-EUAIA-ART14', 'AIGE-OBL-OWASP-AGENTIC', 'AIGE-OBL-CSA-AICM-AGENTIC'],
    pattern: 'human-in-the-loop-gate',
    params: [
      {
        key: 'tool',
        label: 'Tool name',
        hint: 'The tool name as the agent registry and the gateway know it.',
        kind: 'token',
        default: 'refunds-api',
      },
      {
        key: 'operations',
        label: 'Operations that need approval',
        hint: 'Comma-separated. Leave empty to hold every operation of the tool.',
        kind: 'tokens',
        default: 'create_refund',
        optional: true,
      },
    ],
  },
  {
    id: 'model-card-before-release',
    title: 'Model card present before release',
    summary:
      'Fail the merge or the release unless a model card for that exact version has the required sections.',
    statement:
      'A version merges or is released only if a model card for that exact version is present, with the sections {required_sections}.',
    condition:
      'the model card is missing, describes another version or lacks one of {required_sections}',
    effect: 'deny',
    enforcementPoints: ['pre_merge', 'deploy'],
    failureMode:
      'A model ships without the documentation that deployers and reviewers need to use it within its limits.',
    ruleId: 'docs.model-card-present.v1',
    cardId: 'pc-model-card-before-release',
    cardTitle: 'Model card before release',
    appliesTo: ['model:*'],
    sourcePolicy: 'ai-policy.yaml#principles/self-proving',
    obligations: ['AIGE-OBL-EUAIA-ART11', 'AIGE-OBL-EUAIA-ART13', 'AIGE-OBL-ISO42001-A8'],
    pattern: 'model-card-as-control-evidence',
    params: [
      {
        key: 'required_sections',
        label: 'Required model card sections',
        hint: 'Comma-separated section keys your model card template uses.',
        kind: 'tokens',
        default: 'intended_use, limitations, evaluation',
      },
    ],
  },
  {
    id: 'expired-exception-blocks-build',
    title: 'Expired exception blocks the build',
    summary:
      'Fail the build while any policy exception it relies on has expired, has no expiry or runs too long.',
    statement:
      'The build fails while any policy exception it relies on has expired, has no grant or expiry date, or runs longer than {max_days} days.',
    condition:
      'an exception has expired, has no grant or expiry date, or runs longer than {max_days} days',
    effect: 'deny',
    enforcementPoints: ['pre_merge'],
    failureMode:
      'A temporary exception quietly becomes permanent and the rule it waived stops applying.',
    ruleId: 'exceptions.no-expired.v1',
    cardId: 'pc-expired-exception-blocks-build',
    cardTitle: 'Expired exceptions block the build',
    appliesTo: ['repo:*'],
    sourcePolicy: 'ai-policy.yaml#exceptions',
    obligations: ['AIGE-OBL-ISO42001-A2', 'AIGE-OBL-EUAIA-ART17', 'AIGE-OBL-NISTRMF-GOVERN'],
    pattern: 'policy-card',
    params: [
      {
        key: 'max_days',
        label: 'Longest exception allowed, in days',
        hint: 'The AI policy template sets 90.',
        kind: 'int',
        default: '90',
        min: 1,
        max: 730,
      },
    ],
  },
  {
    id: 'custom',
    title: 'Write your own rule',
    summary:
      'One condition on one field of the input: pick the action, the field, the operator, the value and the effect.',
    statement: 'No system whose risk tier is classed as prohibited is deployed.',
    condition: 'for {action}, {field} {operator} {value}',
    effect: 'deny',
    enforcementPoints: ['pre_merge', 'deploy'],
    failureMode: 'A system in a prohibited-practice class reaches production.',
    ruleId: 'custom.rule.v1',
    cardId: 'pc-custom-rule',
    cardTitle: 'Custom rule',
    appliesTo: ['system:*'],
    sourcePolicy: 'ai-policy.yaml#rules/classify-at-intake',
    obligations: ['AIGE-OBL-EUAIA-ART5'],
    pattern: 'policy-card',
    params: [
      {
        key: 'action',
        label: 'Action the rule guards',
        hint: 'The value of the action field in the input, for example deploy, merge or tool_call.',
        kind: 'token',
        default: 'deploy',
      },
      {
        key: 'field',
        label: 'Field of the input',
        hint: 'A dot path in snake_case, for example system.risk_tier.',
        kind: 'path',
        default: 'system.risk_tier',
      },
      {
        key: 'operator',
        label: 'Operator',
        hint: 'Comparison operators never match a missing field; use "is missing" for that.',
        kind: 'operator',
        default: 'equals',
      },
      {
        key: 'value',
        label: 'Value',
        hint: 'A word, a number or true/false. For "is one of", a comma-separated list.',
        kind: 'value',
        default: 'prohibited',
        optional: true,
      },
    ],
  },
];

/** The template for `id`; throws on an unknown id so a page cannot render the wrong one. */
export function policyCardTemplateById(id: string): PolicyCardTemplate {
  const template = policyCardTemplates.find((entry) => entry.id === id);
  if (!template) throw new Error(`policy-card.ts: no template with id "${id}"`);
  return template;
}
