# pc-expired-exception-blocks-build.rego: the executable rule of Policy Card
# pc-expired-exception-blocks-build version 1.0.0.
# Rule exceptions.no-expired.v1 (effect: deny): The build fails while any policy exception it
# relies on has expired, has no grant or expiry date, or runs longer than 90 days.
# Failure mode: A temporary exception quietly becomes permanent and the rule it waived stops
# applying.
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Indicative, not legal advice and not a conformity claim.
# Rego v1 syntax (OPA 1.x). Test it with `opa test`; the `verdict` rule is the record every
# evaluation emits (policy-card.v1.json#/$defs/verdict).
#
# Input: the pipeline or the gateway builds it before it asks OPA. A compliant example:
#   {
#     "action": "build",
#     "now": "2026-10-02",
#     "exceptions": [
#       {
#         "id": "EXC-0042",
#         "rule_id": "evals.min-score.v1",
#         "granted": "2026-10-01",
#         "expires": "2026-12-30",
#         "approved_by_role": "ai-governance-committee"
#       }
#     ]
#   }
package aige.cards.pc_expired_exception_blocks_build

import rego.v1

rule_id := "exceptions.no-expired.v1"

# ---- Parameters (set in the builder) ---------------------------------------------------------

max_days := 90

gated_actions := {"merge", "build"}

ns_per_day := 86400000000000

# ---- Rule exceptions.no-expired.v1 ------------------------------------------------------------

deny contains msg if {
	input.action in gated_actions
	not input.now
	msg := sprintf("%s: the request carries no evaluation date", [rule_id])
}

deny contains msg if {
	input.action in gated_actions
	some exc in input.exceptions
	not exc.expires
	msg := sprintf("%s: exception %s has no expiry", [rule_id, object.get(exc, "id", "(no id)")])
}

deny contains msg if {
	input.action in gated_actions
	some exc in input.exceptions
	not exc.granted
	msg := sprintf("%s: exception %s has no grant date", [rule_id, object.get(exc, "id", "(no id)")])
}

deny contains msg if {
	input.action in gated_actions
	some exc in input.exceptions
	exc.expires < input.now
	msg := sprintf("%s: exception %s expired on %s", [rule_id, object.get(exc, "id", "(no id)"), exc.expires])
}

deny contains msg if {
	input.action in gated_actions
	some exc in input.exceptions
	days := (time.parse_ns("2006-01-02", exc.expires) - time.parse_ns("2006-01-02", exc.granted)) / ns_per_day
	days > max_days
	msg := sprintf("%s: exception %s runs %v days, above the %v-day maximum", [rule_id, object.get(exc, "id", "(no id)"), days, max_days])
}

# ---- Decision and verdict --------------------------------------------------------------------

decision := "deny" if {
	count(deny) > 0
} else := "allow"

# The CI hook fails the job when this is defined (opa eval --fail-defined).
blocks if decision == "deny"

# Sign the verdict where it is written to the evidence store.
verdict := {
	"rule_id": rule_id,
	"decision": decision,
	"input_hash": sprintf("sha256:%s", [crypto.sha256(json.marshal(input))]),
	"timestamp": time.format(time.now_ns()),
}
