# pc-expired-exception-blocks-build_test.rego: unit tests of
# pc-expired-exception-blocks-build.rego.
# Run: opa test policies/pc-expired-exception-blocks-build.rego
# policies/pc-expired-exception-blocks-build_test.rego -v
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Add the cases your own inputs need.
package aige.cards.pc_expired_exception_blocks_build_test

import rego.v1

import data.aige.cards.pc_expired_exception_blocks_build

test_exception_in_date_is_allowed if {
	pc_expired_exception_blocks_build.decision == "allow" with input as {
		"action": "build",
		"now": "2026-10-02",
		"exceptions": [
			{
				"id": "EXC-0042",
				"rule_id": "evals.min-score.v1",
				"granted": "2026-10-01",
				"expires": "2026-12-30",
				"approved_by_role": "ai-governance-committee"
			}
		]
	}
}

test_expired_exception_is_denied if {
	pc_expired_exception_blocks_build.decision == "deny" with input as {
		"action": "build",
		"now": "2026-10-02",
		"exceptions": [
			{
				"id": "EXC-0042",
				"rule_id": "evals.min-score.v1",
				"granted": "2026-09-01",
				"expires": "2026-09-30",
				"approved_by_role": "ai-governance-committee"
			}
		]
	}
}

test_exception_without_expiry_is_denied if {
	pc_expired_exception_blocks_build.decision == "deny" with input as {
		"action": "build",
		"now": "2026-10-02",
		"exceptions": [
			{
				"id": "EXC-0042",
				"rule_id": "evals.min-score.v1",
				"granted": "2026-10-01",
				"approved_by_role": "ai-governance-committee"
			}
		]
	}
}

test_exception_too_long_is_denied if {
	pc_expired_exception_blocks_build.decision == "deny" with input as {
		"action": "build",
		"now": "2026-10-02",
		"exceptions": [
			{
				"id": "EXC-0042",
				"rule_id": "evals.min-score.v1",
				"granted": "2026-10-01",
				"expires": "2026-12-31",
				"approved_by_role": "ai-governance-committee"
			}
		]
	}
}

test_no_exceptions_is_allowed if {
	pc_expired_exception_blocks_build.decision == "allow" with input as {
		"action": "merge",
		"now": "2026-10-02",
		"exceptions": []
	}
}

test_verdict_carries_the_rule_id if {
	v := pc_expired_exception_blocks_build.verdict with input as {
		"action": "build",
		"now": "2026-10-02",
		"exceptions": [
			{
				"id": "EXC-0042",
				"rule_id": "evals.min-score.v1",
				"granted": "2026-10-01",
				"expires": "2026-12-30",
				"approved_by_role": "ai-governance-committee"
			}
		]
	}
	v.rule_id == "exceptions.no-expired.v1"
	v.decision == "allow"
	startswith(v.input_hash, "sha256:")
}

test_compliant_input_does_not_block_ci if {
	not pc_expired_exception_blocks_build.blocks with input as {
		"action": "build",
		"now": "2026-10-02",
		"exceptions": [
			{
				"id": "EXC-0042",
				"rule_id": "evals.min-score.v1",
				"granted": "2026-10-01",
				"expires": "2026-12-30",
				"approved_by_role": "ai-governance-committee"
			}
		]
	}
}

test_denied_input_blocks_ci if {
	pc_expired_exception_blocks_build.blocks with input as {
		"action": "build",
		"now": "2026-10-02",
		"exceptions": [
			{
				"id": "EXC-0042",
				"rule_id": "evals.min-score.v1",
				"granted": "2026-09-01",
				"expires": "2026-09-30",
				"approved_by_role": "ai-governance-committee"
			}
		]
	}
}
