# pc-no-personal-data-external_test.rego: unit tests of pc-no-personal-data-external.rego.
# Run: opa test policies/pc-no-personal-data-external.rego
# policies/pc-no-personal-data-external_test.rego -v
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Add the cases your own inputs need.
package aige.cards.pc_no_personal_data_external_test

import rego.v1

import data.aige.cards.pc_no_personal_data_external

test_unblocked_classes_may_go_external if {
	pc_no_personal_data_external.decision == "allow" with input as {
		"action": "model_call",
		"caller": {
			"id": "support-assistant"
		},
		"model": {
			"id": "vendor-llm",
			"hosting": "external"
		},
		"data_classes": [
			"public",
			"internal"
		]
	}
}

test_blocked_class_to_external_model_is_denied if {
	pc_no_personal_data_external.decision == "deny" with input as {
		"action": "model_call",
		"caller": {
			"id": "support-assistant"
		},
		"model": {
			"id": "vendor-llm",
			"hosting": "external"
		},
		"data_classes": [
			"public",
			"internal",
			"personal"
		]
	}
}

test_unclassified_request_is_denied if {
	pc_no_personal_data_external.decision == "deny" with input as {
		"action": "model_call",
		"caller": {
			"id": "support-assistant"
		},
		"model": {
			"id": "vendor-llm",
			"hosting": "external"
		}
	}
}

test_blocked_class_to_internal_model_is_allowed if {
	pc_no_personal_data_external.decision == "allow" with input as {
		"action": "model_call",
		"caller": {
			"id": "support-assistant"
		},
		"model": {
			"id": "internal-llm",
			"hosting": "internal"
		},
		"data_classes": [
			"personal"
		]
	}
}

test_verdict_carries_the_rule_id if {
	v := pc_no_personal_data_external.verdict with input as {
		"action": "model_call",
		"caller": {
			"id": "support-assistant"
		},
		"model": {
			"id": "vendor-llm",
			"hosting": "external"
		},
		"data_classes": [
			"public",
			"internal"
		]
	}
	v.rule_id == "data.no-personal-data-external.v1"
	v.decision == "allow"
	startswith(v.input_hash, "sha256:")
}

test_compliant_input_does_not_block_ci if {
	not pc_no_personal_data_external.blocks with input as {
		"action": "model_call",
		"caller": {
			"id": "support-assistant"
		},
		"model": {
			"id": "vendor-llm",
			"hosting": "external"
		},
		"data_classes": [
			"public",
			"internal"
		]
	}
}

test_denied_input_blocks_ci if {
	pc_no_personal_data_external.blocks with input as {
		"action": "model_call",
		"caller": {
			"id": "support-assistant"
		},
		"model": {
			"id": "vendor-llm",
			"hosting": "external"
		},
		"data_classes": [
			"public",
			"internal",
			"personal"
		]
	}
}
