# pc-no-personal-data-external.rego: the executable rule of Policy Card
# pc-no-personal-data-external version 1.0.0.
# Rule data.no-personal-data-external.v1 (effect: deny): No request that carries personal,
# special_category data is sent to a model hosted outside the organisation; a request without a
# data classification is treated as carrying it.
# Failure mode: Personal data leaves the organisation in a prompt to a third-party model.
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Indicative, not legal advice and not a conformity claim.
# Rego v1 syntax (OPA 1.x). Test it with `opa test`; the `verdict` rule is the record every
# evaluation emits (policy-card.v1.json#/$defs/verdict).
#
# Input: the pipeline or the gateway builds it before it asks OPA. A compliant example:
#   {
#     "action": "model_call",
#     "caller": {
#       "id": "support-assistant"
#     },
#     "model": {
#       "id": "vendor-llm",
#       "hosting": "external"
#     },
#     "data_classes": [
#       "public",
#       "internal"
#     ]
#   }
package aige.cards.pc_no_personal_data_external

import rego.v1

rule_id := "data.no-personal-data-external.v1"

# ---- Parameters (set in the builder) ---------------------------------------------------------

blocked_classes := {"personal", "special_category"}

# ---- Rule data.no-personal-data-external.v1 ---------------------------------------------------

internal_model if input.model.hosting == "internal"

deny contains msg if {
	input.action == "model_call"
	not internal_model
	some class in input.data_classes
	class in blocked_classes
	msg := sprintf("%s: %s data may not be sent to a model hosted outside the organisation", [rule_id, class])
}

deny contains msg if {
	input.action == "model_call"
	not internal_model
	not input.data_classes
	msg := sprintf("%s: the request carries no data classification, so it may not leave the organisation", [rule_id])
}

# ---- Decision and verdict --------------------------------------------------------------------

decision := "deny" if {
	count(deny) > 0
} else := "allow"

# The CI hook fails the job when this is defined (opa eval --fail-defined).
blocks if decision == "deny"

# Sign the verdict where it is written to the evidence store.
verdict := {
	"rule_id": rule_id,
	"decision": decision,
	"input_hash": sprintf("sha256:%s", [crypto.sha256(json.marshal(input))]),
	"timestamp": time.format(time.now_ns()),
}
