# pc-registered-agents-only.rego: the executable rule of Policy Card pc-registered-agents-only
# version 1.0.0.
# Rule agents.registered-only.v1 (effect: deny): No agent runs in production unless it has an
# active entry in the agent registry, with an owner and an expiry that has not passed.
# Failure mode: An agent that nobody owns or bounded acts in production (a shadow agent).
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Indicative, not legal advice and not a conformity claim.
# Rego v1 syntax (OPA 1.x). Test it with `opa test`; the `verdict` rule is the record every
# evaluation emits (policy-card.v1.json#/$defs/verdict).
#
# Input: the pipeline or the gateway builds it before it asks OPA. A compliant example:
#   {
#     "action": "deploy",
#     "environment": "production",
#     "now": "2026-10-02",
#     "agent": {
#       "id": "csa-01",
#       "version": "2026-09-22"
#     },
#     "registry": [
#       {
#         "id": "csa-01",
#         "version": "2026-09-22",
#         "owner": "customer-service",
#         "scope": [
#           "refunds"
#         ],
#         "expiry": "2027-03-31",
#         "status": "active"
#       }
#     ]
#   }
package aige.cards.pc_registered_agents_only

import rego.v1

rule_id := "agents.registered-only.v1"

# ---- Parameters (set in the builder) ---------------------------------------------------------

environment := "production"

# ---- Rule agents.registered-only.v1 -----------------------------------------------------------

in_scope if input.environment == environment

entries contains e if {
	some e in input.registry
	e.id == input.agent.id
}

active(e) if e.status == "active"

deny contains msg if {
	in_scope
	not input.agent.id
	msg := sprintf("%s: the request names no agent", [rule_id])
}

deny contains msg if {
	in_scope
	not input.now
	msg := sprintf("%s: the request carries no evaluation date", [rule_id])
}

deny contains msg if {
	in_scope
	input.agent.id
	count(entries) == 0
	msg := sprintf("%s: agent %s has no entry in the agent registry", [rule_id, input.agent.id])
}

deny contains msg if {
	in_scope
	some e in entries
	not active(e)
	msg := sprintf("%s: registry entry %s is not active", [rule_id, e.id])
}

deny contains msg if {
	in_scope
	some e in entries
	not e.owner
	msg := sprintf("%s: registry entry %s names no owner", [rule_id, e.id])
}

deny contains msg if {
	in_scope
	some e in entries
	not e.expiry
	msg := sprintf("%s: registry entry %s has no expiry", [rule_id, e.id])
}

deny contains msg if {
	in_scope
	some e in entries
	e.expiry < input.now
	msg := sprintf("%s: registry entry %s expired on %s", [rule_id, e.id, e.expiry])
}

# ---- Decision and verdict --------------------------------------------------------------------

decision := "deny" if {
	count(deny) > 0
} else := "allow"

# The CI hook fails the job when this is defined (opa eval --fail-defined).
blocks if decision == "deny"

# Sign the verdict where it is written to the evidence store.
verdict := {
	"rule_id": rule_id,
	"decision": decision,
	"input_hash": sprintf("sha256:%s", [crypto.sha256(json.marshal(input))]),
	"timestamp": time.format(time.now_ns()),
}
