# pc-registered-agents-only_test.rego: unit tests of pc-registered-agents-only.rego.
# Run: opa test policies/pc-registered-agents-only.rego
# policies/pc-registered-agents-only_test.rego -v
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Add the cases your own inputs need.
package aige.cards.pc_registered_agents_only_test

import rego.v1

import data.aige.cards.pc_registered_agents_only

test_registered_active_agent_is_allowed if {
	pc_registered_agents_only.decision == "allow" with input as {
		"action": "deploy",
		"environment": "production",
		"now": "2026-10-02",
		"agent": {
			"id": "csa-01",
			"version": "2026-09-22"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "active"
			}
		]
	}
}

test_unregistered_agent_is_denied if {
	pc_registered_agents_only.decision == "deny" with input as {
		"action": "deploy",
		"environment": "production",
		"now": "2026-10-02",
		"agent": {
			"id": "shadow-07",
			"version": "0.1.0"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "active"
			}
		]
	}
}

test_expired_entry_is_denied if {
	pc_registered_agents_only.decision == "deny" with input as {
		"action": "deploy",
		"environment": "production",
		"now": "2026-10-02",
		"agent": {
			"id": "csa-01",
			"version": "2026-09-22"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2026-09-30",
				"status": "active"
			}
		]
	}
}

test_suspended_entry_is_denied if {
	pc_registered_agents_only.decision == "deny" with input as {
		"action": "deploy",
		"environment": "production",
		"now": "2026-10-02",
		"agent": {
			"id": "csa-01",
			"version": "2026-09-22"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "suspended"
			}
		]
	}
}

test_missing_date_is_denied if {
	pc_registered_agents_only.decision == "deny" with input as {
		"action": "deploy",
		"environment": "production",
		"agent": {
			"id": "csa-01",
			"version": "2026-09-22"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "active"
			}
		]
	}
}

test_other_environment_is_out_of_scope if {
	pc_registered_agents_only.decision == "allow" with input as {
		"action": "deploy",
		"environment": "staging",
		"now": "2026-10-02",
		"agent": {
			"id": "shadow-07",
			"version": "0.1.0"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "active"
			}
		]
	}
}

test_verdict_carries_the_rule_id if {
	v := pc_registered_agents_only.verdict with input as {
		"action": "deploy",
		"environment": "production",
		"now": "2026-10-02",
		"agent": {
			"id": "csa-01",
			"version": "2026-09-22"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "active"
			}
		]
	}
	v.rule_id == "agents.registered-only.v1"
	v.decision == "allow"
	startswith(v.input_hash, "sha256:")
}

test_compliant_input_does_not_block_ci if {
	not pc_registered_agents_only.blocks with input as {
		"action": "deploy",
		"environment": "production",
		"now": "2026-10-02",
		"agent": {
			"id": "csa-01",
			"version": "2026-09-22"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "active"
			}
		]
	}
}

test_denied_input_blocks_ci if {
	pc_registered_agents_only.blocks with input as {
		"action": "deploy",
		"environment": "production",
		"now": "2026-10-02",
		"agent": {
			"id": "shadow-07",
			"version": "0.1.0"
		},
		"registry": [
			{
				"id": "csa-01",
				"version": "2026-09-22",
				"owner": "customer-service",
				"scope": [
					"refunds"
				],
				"expiry": "2027-03-31",
				"status": "active"
			}
		]
	}
}
