# pc-custom-rule_test.rego: unit tests of pc-custom-rule.rego.
# Run: opa test policies/pc-custom-rule.rego policies/pc-custom-rule_test.rego -v
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Add the cases your own inputs need.
package aige.cards.pc_custom_rule_test

import rego.v1

import data.aige.cards.pc_custom_rule

test_input_that_does_not_match_gets_the_default if {
	pc_custom_rule.decision == "allow" with input as {
		"action": "deploy",
		"system": {
			"risk_tier": "prohibited-other"
		}
	}
}

test_input_that_matches_gets_the_effect if {
	pc_custom_rule.decision == "deny" with input as {
		"action": "deploy",
		"system": {
			"risk_tier": "prohibited"
		}
	}
}

test_other_action_is_out_of_scope if {
	pc_custom_rule.decision == "allow" with input as {
		"action": "deploy-other",
		"system": {
			"risk_tier": "prohibited"
		}
	}
}

test_verdict_carries_the_rule_id if {
	v := pc_custom_rule.verdict with input as {
		"action": "deploy",
		"system": {
			"risk_tier": "prohibited-other"
		}
	}
	v.rule_id == "custom.rule.v1"
	v.decision == "allow"
	startswith(v.input_hash, "sha256:")
}

test_compliant_input_does_not_block_ci if {
	not pc_custom_rule.blocks with input as {
		"action": "deploy",
		"system": {
			"risk_tier": "prohibited-other"
		}
	}
}

test_denied_input_blocks_ci if {
	pc_custom_rule.blocks with input as {
		"action": "deploy",
		"system": {
			"risk_tier": "prohibited"
		}
	}
}
