# pc-custom-rule.rego: the executable rule of Policy Card pc-custom-rule version 1.0.0.
# Rule custom.rule.v1 (effect: deny): No system whose risk tier is classed as prohibited is
# deployed.
# Failure mode: A system in a prohibited-practice class reaches production.
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Indicative, not legal advice and not a conformity claim.
# Rego v1 syntax (OPA 1.x). Test it with `opa test`; the `verdict` rule is the record every
# evaluation emits (policy-card.v1.json#/$defs/verdict).
#
# Input: the pipeline or the gateway builds it before it asks OPA. A compliant example:
#   {
#     "action": "deploy",
#     "system": {
#       "risk_tier": "prohibited-other"
#     }
#   }
package aige.cards.pc_custom_rule

import rego.v1

rule_id := "custom.rule.v1"

# ---- Parameters (set in the builder) ---------------------------------------------------------

guarded_action := "deploy"

# ---- Rule custom.rule.v1 ----------------------------------------------------------------------

deny contains msg if {
	input.action == guarded_action
	input.system.risk_tier == "prohibited"
	msg := sprintf("%s: %s", [rule_id, "system.risk_tier equals prohibited"])
}

# ---- Decision and verdict --------------------------------------------------------------------

decision := "deny" if {
	count(deny) > 0
} else := "allow"

# The CI hook fails the job when this is defined (opa eval --fail-defined).
blocks if decision == "deny"

# Sign the verdict where it is written to the evidence store.
verdict := {
	"rule_id": rule_id,
	"decision": decision,
	"input_hash": sprintf("sha256:%s", [crypto.sha256(json.marshal(input))]),
	"timestamp": time.format(time.now_ns()),
}
