blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/losanchos5/aige/discussions
    about: Ask a question or start a conversation about the Thesis and Body of Knowledge.
