# pc-model-card-before-release_test.rego: unit tests of pc-model-card-before-release.rego.
# Run: opa test policies/pc-model-card-before-release.rego
# policies/pc-model-card-before-release_test.rego -v
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Add the cases your own inputs need.
package aige.cards.pc_model_card_before_release_test

import rego.v1

import data.aige.cards.pc_model_card_before_release

test_complete_card_for_the_version_is_allowed if {
	pc_model_card_before_release.decision == "allow" with input as {
		"action": "release",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		},
		"model_card": {
			"model_version": "credit-afford@3.2.0",
			"sections": [
				"intended_use",
				"limitations",
				"evaluation",
				"training_data-other"
			]
		}
	}
}

test_missing_card_is_denied if {
	pc_model_card_before_release.decision == "deny" with input as {
		"action": "release",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		}
	}
}

test_missing_section_is_denied if {
	pc_model_card_before_release.decision == "deny" with input as {
		"action": "release",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		},
		"model_card": {
			"model_version": "credit-afford@3.2.0",
			"sections": [
				"intended_use",
				"limitations",
				"training_data-other"
			]
		}
	}
}

test_card_for_another_version_is_denied if {
	pc_model_card_before_release.decision == "deny" with input as {
		"action": "release",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		},
		"model_card": {
			"model_version": "credit-afford@3.1.0",
			"sections": [
				"intended_use",
				"limitations",
				"evaluation",
				"training_data-other"
			]
		}
	}
}

test_merge_is_gated_too if {
	pc_model_card_before_release.decision == "deny" with input as {
		"action": "merge",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		}
	}
}

test_verdict_carries_the_rule_id if {
	v := pc_model_card_before_release.verdict with input as {
		"action": "release",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		},
		"model_card": {
			"model_version": "credit-afford@3.2.0",
			"sections": [
				"intended_use",
				"limitations",
				"evaluation",
				"training_data-other"
			]
		}
	}
	v.rule_id == "docs.model-card-present.v1"
	v.decision == "allow"
	startswith(v.input_hash, "sha256:")
}

test_compliant_input_does_not_block_ci if {
	not pc_model_card_before_release.blocks with input as {
		"action": "release",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		},
		"model_card": {
			"model_version": "credit-afford@3.2.0",
			"sections": [
				"intended_use",
				"limitations",
				"evaluation",
				"training_data-other"
			]
		}
	}
}

test_denied_input_blocks_ci if {
	pc_model_card_before_release.blocks with input as {
		"action": "release",
		"system": {
			"id": "credit-afford",
			"version": "3.2.0"
		}
	}
}
