# pc-model-card-before-release.rego: the executable rule of Policy Card
# pc-model-card-before-release version 1.0.0.
# Rule docs.model-card-present.v1 (effect: deny): A version merges or is released only if a model
# card for that exact version is present, with the sections intended_use, limitations, evaluation.
# Failure mode: A model ships without the documentation that deployers and reviewers need to use it
# within its limits.
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Indicative, not legal advice and not a conformity claim.
# Rego v1 syntax (OPA 1.x). Test it with `opa test`; the `verdict` rule is the record every
# evaluation emits (policy-card.v1.json#/$defs/verdict).
#
# Input: the pipeline or the gateway builds it before it asks OPA. A compliant example:
#   {
#     "action": "release",
#     "system": {
#       "id": "credit-afford",
#       "version": "3.2.0"
#     },
#     "model_card": {
#       "model_version": "credit-afford@3.2.0",
#       "sections": [
#         "intended_use",
#         "limitations",
#         "evaluation",
#         "training_data-other"
#       ]
#     }
#   }
package aige.cards.pc_model_card_before_release

import rego.v1

rule_id := "docs.model-card-present.v1"

# ---- Parameters (set in the builder) ---------------------------------------------------------

required_sections := {"intended_use", "limitations", "evaluation"}

gated_actions := {"merge", "release"}

# ---- Rule docs.model-card-present.v1 ----------------------------------------------------------

subject := sprintf("%s@%s", [input.system.id, input.system.version])

card_for_subject if input.model_card.model_version == subject

deny contains msg if {
	input.action in gated_actions
	not subject
	msg := sprintf("%s: the request names no system id and version", [rule_id])
}

deny contains msg if {
	input.action in gated_actions
	not input.model_card
	msg := sprintf("%s: %s has no model card", [rule_id, subject])
}

deny contains msg if {
	input.action in gated_actions
	input.model_card
	not card_for_subject
	msg := sprintf("%s: the model card does not describe %s", [rule_id, subject])
}

deny contains msg if {
	input.action in gated_actions
	input.model_card
	some section in required_sections
	not section in object.get(input.model_card, "sections", [])
	msg := sprintf("%s: the model card for %s has no %s section", [rule_id, subject, section])
}

# ---- Decision and verdict --------------------------------------------------------------------

decision := "deny" if {
	count(deny) > 0
} else := "allow"

# The CI hook fails the job when this is defined (opa eval --fail-defined).
blocks if decision == "deny"

# Sign the verdict where it is written to the evidence store.
verdict := {
	"rule_id": rule_id,
	"decision": decision,
	"input_hash": sprintf("sha256:%s", [crypto.sha256(json.marshal(input))]),
	"timestamp": time.format(time.now_ns()),
}
