# pc-approval-for-tool.rego: the executable rule of Policy Card pc-approval-for-tool version 1.0.0.
# Rule tools.approval-required.v1 (effect: require_approval): An agent calls refunds-api
# (create_refund) only with a recorded approval by a person other than the agent.
# Failure mode: An agent takes a consequential action through a tool with no human in the loop.
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Indicative, not legal advice and not a conformity claim.
# Rego v1 syntax (OPA 1.x). Test it with `opa test`; the `verdict` rule is the record every
# evaluation emits (policy-card.v1.json#/$defs/verdict).
#
# Input: the pipeline or the gateway builds it before it asks OPA. A compliant example:
#   {
#     "action": "tool_call",
#     "agent": {
#       "id": "csa-01"
#     },
#     "call": {
#       "tool": "refunds-api",
#       "operation": "create_refund"
#     },
#     "approval": {
#       "status": "approved",
#       "approved_by": "team-lead-07",
#       "ticket": "APR-1042"
#     }
#   }
package aige.cards.pc_approval_for_tool

import rego.v1

rule_id := "tools.approval-required.v1"

# ---- Parameters (set in the builder) ---------------------------------------------------------

tool := "refunds-api"

# An empty set holds every operation of the tool.
operations := {"create_refund"}

# ---- Rule tools.approval-required.v1 ----------------------------------------------------------

governed if {
	input.action == "tool_call"
	input.call.tool == tool
	count(operations) == 0
}

governed if {
	input.action == "tool_call"
	input.call.tool == tool
	input.call.operation in operations
}

# Approved by a person other than the agent that makes the call.
approved if {
	input.approval.status == "approved"
	input.approval.approved_by != input.agent.id
}

require_approval contains msg if {
	governed
	not approved
	msg := sprintf("%s: this call to %s needs a recorded approval by a person other than the agent", [rule_id, tool])
}

# ---- Decision and verdict --------------------------------------------------------------------

decision := "require_approval" if {
	count(require_approval) > 0
} else := "allow"

# The CI hook fails the job when this is defined (opa eval --fail-defined).
blocks if decision == "deny"

# Sign the verdict where it is written to the evidence store.
verdict := {
	"rule_id": rule_id,
	"decision": decision,
	"input_hash": sprintf("sha256:%s", [crypto.sha256(json.marshal(input))]),
	"timestamp": time.format(time.now_ns()),
}
