# pc-approval-for-tool_test.rego: unit tests of pc-approval-for-tool.rego.
# Run: opa test policies/pc-approval-for-tool.rego policies/pc-approval-for-tool_test.rego -v
# Generated by the Policy Card builder, https://aigovernanceengineer.com/toolkit/policy-card
# Illustrative, review before use. Add the cases your own inputs need.
package aige.cards.pc_approval_for_tool_test

import rego.v1

import data.aige.cards.pc_approval_for_tool

test_approved_call_is_allowed if {
	pc_approval_for_tool.decision == "allow" with input as {
		"action": "tool_call",
		"agent": {
			"id": "csa-01"
		},
		"call": {
			"tool": "refunds-api",
			"operation": "create_refund"
		},
		"approval": {
			"status": "approved",
			"approved_by": "team-lead-07",
			"ticket": "APR-1042"
		}
	}
}

test_call_without_approval_is_held if {
	pc_approval_for_tool.decision == "require_approval" with input as {
		"action": "tool_call",
		"agent": {
			"id": "csa-01"
		},
		"call": {
			"tool": "refunds-api",
			"operation": "create_refund"
		}
	}
}

test_self_approved_call_is_held if {
	pc_approval_for_tool.decision == "require_approval" with input as {
		"action": "tool_call",
		"agent": {
			"id": "csa-01"
		},
		"call": {
			"tool": "refunds-api",
			"operation": "create_refund"
		},
		"approval": {
			"status": "approved",
			"approved_by": "csa-01",
			"ticket": "APR-1043"
		}
	}
}

test_other_tool_is_out_of_scope if {
	pc_approval_for_tool.decision == "allow" with input as {
		"action": "tool_call",
		"agent": {
			"id": "csa-01"
		},
		"call": {
			"tool": "refunds-api-other",
			"operation": "create_refund"
		}
	}
}

test_other_operation_is_out_of_scope if {
	pc_approval_for_tool.decision == "allow" with input as {
		"action": "tool_call",
		"agent": {
			"id": "csa-01"
		},
		"call": {
			"tool": "refunds-api",
			"operation": "create_refund-other"
		}
	}
}

test_verdict_carries_the_rule_id if {
	v := pc_approval_for_tool.verdict with input as {
		"action": "tool_call",
		"agent": {
			"id": "csa-01"
		},
		"call": {
			"tool": "refunds-api",
			"operation": "create_refund"
		},
		"approval": {
			"status": "approved",
			"approved_by": "team-lead-07",
			"ticket": "APR-1042"
		}
	}
	v.rule_id == "tools.approval-required.v1"
	v.decision == "allow"
	startswith(v.input_hash, "sha256:")
}

test_compliant_input_does_not_block_ci if {
	not pc_approval_for_tool.blocks with input as {
		"action": "tool_call",
		"agent": {
			"id": "csa-01"
		},
		"call": {
			"tool": "refunds-api",
			"operation": "create_refund"
		},
		"approval": {
			"status": "approved",
			"approved_by": "team-lead-07",
			"ticket": "APR-1042"
		}
	}
}
