// catalogue.generated.ts: GENERATED by scripts/sync-catalogue.mjs from the site
// sources (site/public/schemas, site/public/templates, site/src/data/templates.ts).
// Do not edit by hand: run `npm run catalogue` in tools/mcp-server.

import type { TemplateEntry } from './catalogue.js';

export const catalogue: readonly TemplateEntry[] = [
  {
    "name": "use-case-record",
    "kind": "schema",
    "title": "Use-case record",
    "description": "The intake record for a proposed AI use: the problem, the intended purpose and its limits, who is affected, whether AI is the right tool, the preliminary classification and which assessments it triggers. Scaffolds the register entry.",
    "stage": "intake",
    "stageLabel": "Intake and inventory",
    "layers": [
      1,
      2
    ],
    "patterns": [
      "pattern-fria-as-code",
      "pattern-agent-registry",
      "pattern-use-case-intake--risk-tiering"
    ],
    "evidences": [
      "EU AI Act Art. 6",
      "EU AI Act Art. 9(2)",
      "EU AI Act Art. 27",
      "GDPR Art. 35",
      "ISO/IEC 42001 A.5",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF MAP 1.1",
      "NIST AI RMF MAP 3.3"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/use-case-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/use-case-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/use-case-record.md"
      }
    ]
  },
  {
    "name": "classification-decision-record",
    "kind": "schema",
    "title": "Classification decision record",
    "description": "The recorded EU AI Act triage of one AI system or model: the question set and version it was answered against, every answer with its article and meaning, the indicative scope, operator roles and risk classes with their reasons, the high-risk screen with the Art. 6(3) condition and the explicit profiling flag, the reviewer, the date, the legal-review state and the events that re-open it.",
    "stage": "intake",
    "stageLabel": "Intake and inventory",
    "layers": [
      1,
      2
    ],
    "patterns": [
      "pattern-policy-card",
      "pattern-agent-registry"
    ],
    "evidences": [
      "EU AI Act Art. 6(3)",
      "EU AI Act Art. 6(4)",
      "EU AI Act Art. 49(2)",
      "EU AI Act Art. 25",
      "EU AI Act Art. 2",
      "EU AI Act Art. 5",
      "EU AI Act Art. 50",
      "EU AI Act Art. 52"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/classification-decision-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/classification-decision-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/classification-decision-record.md"
      }
    ]
  },
  {
    "name": "ai-system-register-entry",
    "kind": "schema",
    "title": "AI system register entry",
    "description": "One entry in the inventory of AI systems and models: who owns it, what it may do, how it is classified and where its evidence lives. The deploy pipeline writes the core fields; intake adds the classification. Extends the registry entry shape in chapter 05 (id, version, owner, scope, expiry).",
    "stage": "intake",
    "stageLabel": "Intake and inventory",
    "layers": [
      2
    ],
    "patterns": [
      "pattern-agent-registry",
      "pattern-shadow-ai-discovery"
    ],
    "evidences": [
      "EU AI Act Art. 49",
      "EU AI Act Art. 71",
      "EU AI Act Art. 6",
      "EU AI Act Art. 26",
      "ISO/IEC 42001 A.4",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF GOVERN 1.6"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/ai-system-register-entry.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/ai-system-register-entry.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/ai-system-register-entry.md"
      }
    ]
  },
  {
    "name": "agent-register-entry",
    "kind": "schema",
    "title": "Agent register entry",
    "description": "One entry in the agent registry: a non-human actor with an owner, a declared scope, a workload identity, bounded tools and a kill switch. Same core as the registry entry in chapter 05 (id, version, owner, scope, expiry), with the fields runtime controls need.",
    "stage": "intake",
    "stageLabel": "Intake and inventory",
    "layers": [
      2,
      4
    ],
    "patterns": [
      "pattern-agent-registry",
      "pattern-agent-identity--scoped-credentials",
      "pattern-kill-switch--circuit-breaker"
    ],
    "evidences": [
      "EU AI Act Art. 14",
      "EU AI Act Art. 12",
      "EU AI Act Art. 26",
      "ISO/IEC 42001 A.6",
      "ISO/IEC 42001 A.9",
      "NIST AI RMF GOVERN 1.6",
      "NIST AI RMF MANAGE 2.4"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/agent-register-entry.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/agent-register-entry.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/agent-register-entry.md"
      }
    ]
  },
  {
    "name": "impact-assessment",
    "kind": "schema",
    "title": "Impact assessment",
    "description": "One schema for three assessments, told apart by `type`: an AI system impact assessment (aiia), an AI addendum to a data protection impact assessment (dpia_addendum) and a fundamental rights impact assessment (fria). Shared fields carry the risks, mitigations and outcome; type-specific fields carry what each instrument asks for.",
    "stage": "intake",
    "stageLabel": "Intake and inventory",
    "layers": [
      1,
      2
    ],
    "patterns": [
      "pattern-fria-as-code"
    ],
    "evidences": [
      "EU AI Act Art. 27",
      "EU AI Act Art. 27(1)",
      "EU AI Act Art. 27(3)",
      "EU AI Act Art. 27(4)",
      "GDPR Art. 35",
      "GDPR Art. 35(7)",
      "ISO/IEC 42005",
      "ISO/IEC 42001 A.5",
      "NIST AI RMF MAP 5.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/impact-assessment.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/impact-assessment.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/impact-assessment.md"
      }
    ]
  },
  {
    "name": "vendor-due-diligence-response",
    "kind": "schema",
    "title": "Vendor due-diligence response",
    "description": "A supplier's answers to the AI due-diligence questionnaire for one product, keyed to the obligations they help the buyer evidence, plus the buyer's assessment and reassessment date.",
    "stage": "intake",
    "stageLabel": "Intake and inventory",
    "layers": [
      2,
      5
    ],
    "patterns": [
      "pattern-vendor--model-due-diligence-gate"
    ],
    "evidences": [
      "EU AI Act Art. 25",
      "EU AI Act Art. 26",
      "EU AI Act Art. 53(1)(b)",
      "GDPR Art. 28",
      "ISO/IEC 42001 A.10",
      "NIST AI RMF GOVERN 6.1",
      "NIST AI RMF MANAGE 3.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/vendor-due-diligence-response.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/vendor-due-diligence-response.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/vendor-due-diligence-response.md"
      }
    ]
  },
  {
    "name": "design-record",
    "kind": "schema",
    "title": "Design record",
    "description": "The design review of one AI system version: requirements traced to their source, the model-selection trade-off, the oversight and logging designed in, and the metrics and thresholds the release will be judged on.",
    "stage": "build",
    "stageLabel": "Design and data",
    "layers": [
      1,
      3
    ],
    "patterns": [
      "pattern-human-in-the-loop-gate",
      "pattern-kill-switch--circuit-breaker",
      "pattern-eval-gate-in-ci"
    ],
    "evidences": [
      "EU AI Act Art. 9",
      "EU AI Act Art. 11",
      "EU AI Act Annex IV",
      "EU AI Act Art. 12",
      "EU AI Act Art. 14",
      "EU AI Act Art. 15",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF MAP 1.6",
      "NIST AI RMF MAP 3.5"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/design-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/design-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/design-record.md"
      }
    ]
  },
  {
    "name": "dataset-card",
    "kind": "schema",
    "title": "Dataset card",
    "description": "The card that travels with a dataset: what it contains, where it came from, the right to use it, how representative it is, how it was checked and when it must be deleted. Datasheet-style documentation made machine-readable.",
    "stage": "build",
    "stageLabel": "Design and data",
    "layers": [
      2
    ],
    "patterns": [
      "pattern-aibom",
      "pattern-model-card-as-control-evidence",
      "pattern-training-data-rights-ledger"
    ],
    "evidences": [
      "EU AI Act Art. 10",
      "EU AI Act Art. 4a",
      "EU AI Act Art. 53(1)(d)",
      "GDPR Art. 6",
      "GDPR Art. 9",
      "ISO/IEC 42001 A.7",
      "NIST AI RMF MAP 4.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/dataset-card.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/dataset-card.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/dataset-card.md"
      }
    ]
  },
  {
    "name": "model-card",
    "kind": "schema",
    "title": "Model card",
    "description": "A model or system card as a record: what the model is, what it is for and not for, the data it was built and tested on, how it performs across groups and conditions, its limits, and the links to the rest of the technical file. The same record renders a Hugging Face style card and a CycloneDX ML-BOM component, so the card an auditor reads is the card production produced.",
    "stage": "build",
    "stageLabel": "Design and data",
    "layers": [
      2
    ],
    "patterns": [
      "pattern-model-card-as-control-evidence",
      "pattern-aibom"
    ],
    "evidences": [
      "EU AI Act Art. 11",
      "EU AI Act Annex IV",
      "EU AI Act Art. 13",
      "EU AI Act Art. 53(1)(a)",
      "EU AI Act Art. 53(1)(b)",
      "ISO/IEC 42001 A.6",
      "ISO/IEC 42001 A.8",
      "NIST AI RMF MAP 1.1",
      "NIST AI RMF MEASURE 2.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/model-card.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/model-card.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/model-card.md"
      }
    ]
  },
  {
    "name": "dataset-admission-record",
    "kind": "schema",
    "title": "Dataset admission record",
    "description": "The verdict of the dataset admission gate: whether one dataset version may enter one pipeline, which checks ran and who or what decided. Shaped like the evidence record in chapter 05 (control_id, subject, decision, input_hash, actor, timestamp, signature).",
    "stage": "build",
    "stageLabel": "Design and data",
    "layers": [
      3
    ],
    "patterns": [
      "pattern-eval-gate-in-ci",
      "pattern-aibom",
      "pattern-dataset-admission-gate"
    ],
    "evidences": [
      "EU AI Act Art. 10",
      "ISO/IEC 42001 A.7",
      "NIST AI RMF MAP 4.1",
      "NIST AI RMF MEASURE 2.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/dataset-admission-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/dataset-admission-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/dataset-admission-record.md"
      }
    ]
  },
  {
    "name": "test-plan",
    "kind": "schema",
    "title": "Test plan",
    "description": "What will be tested before a release and how the release will be judged: suites by category, each with its metric, threshold and failure mode, set before testing starts.",
    "stage": "test",
    "stageLabel": "Test and evaluate",
    "layers": [
      3
    ],
    "patterns": [
      "pattern-eval-gate-in-ci",
      "pattern-adversarial-red-team-suite"
    ],
    "evidences": [
      "EU AI Act Art. 9(6)",
      "EU AI Act Art. 9(8)",
      "EU AI Act Art. 15",
      "EU AI Act Art. 60",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF MEASURE 2.1",
      "NIST AI RMF MEASURE 2.11"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/test-plan.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/test-plan.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/test-plan.md"
      }
    ]
  },
  {
    "name": "eval-result",
    "kind": "schema",
    "title": "Eval result",
    "description": "The structured result of one eval suite run against one system version, filed against its registry entry. Exactly the shape published in chapter 05 (suite_id, model_version, score, threshold, result, timestamp), with optional fields for direction, failure mode and provenance.",
    "stage": "test",
    "stageLabel": "Test and evaluate",
    "layers": [
      3
    ],
    "patterns": [
      "pattern-eval-gate-in-ci",
      "pattern-adversarial-red-team-suite",
      "pattern-fairness-eval-suite"
    ],
    "evidences": [
      "EU AI Act Art. 15",
      "EU AI Act Art. 9(8)",
      "EU AI Act Art. 55",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF MEASURE 2.3",
      "NIST AI RMF MEASURE 2.5"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/eval-result.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/eval-result.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/eval-result.md"
      }
    ]
  },
  {
    "name": "test-report",
    "kind": "schema",
    "title": "Test report",
    "description": "The dated, signed report of a test campaign: the eval results against the plan, deviations and waivers, and the conclusion the go/no-go reads.",
    "stage": "test",
    "stageLabel": "Test and evaluate",
    "layers": [
      3
    ],
    "patterns": [
      "pattern-eval-gate-in-ci",
      "pattern-adversarial-red-team-suite"
    ],
    "evidences": [
      "EU AI Act Annex IV(2)(g)",
      "EU AI Act Art. 9(8)",
      "EU AI Act Art. 15",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF MEASURE 2.3",
      "NIST AI RMF MEASURE 2.13"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/test-report.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/test-report.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/test-report.md"
      }
    ]
  },
  {
    "name": "go-no-go",
    "kind": "schema",
    "title": "Go/no-go decision",
    "description": "The release gate for one system version: a checklist whose items name the obligation they evidence and the record that proves them, the reviewers' decisions by role, any overrides, and the rollout and rollback plan.",
    "stage": "release",
    "stageLabel": "Release and deploy",
    "layers": [
      3,
      5
    ],
    "patterns": [
      "pattern-eval-gate-in-ci",
      "pattern-human-in-the-loop-gate",
      "pattern-staged-rollout-with-rollback-criteria"
    ],
    "evidences": [
      "EU AI Act Art. 9",
      "EU AI Act Art. 17",
      "EU AI Act Art. 43",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF MANAGE 1.1",
      "NIST AI RMF MANAGE 1.4"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/go-no-go.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/go-no-go.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/go-no-go.md"
      }
    ]
  },
  {
    "name": "instructions-for-use",
    "kind": "schema",
    "title": "Instructions for use",
    "description": "The information a provider gives deployers so they can use a high-risk system correctly, one field per element the EU AI Act lists for instructions for use. Generated from the register entry, design record and test report, then reviewed.",
    "stage": "release",
    "stageLabel": "Release and deploy",
    "layers": [
      2
    ],
    "patterns": [
      "pattern-model-card-as-control-evidence"
    ],
    "evidences": [
      "EU AI Act Art. 13",
      "EU AI Act Art. 13(3)",
      "EU AI Act Art. 26(1)",
      "ISO/IEC 42001 A.8",
      "NIST AI RMF MAP 2.2"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/instructions-for-use.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/instructions-for-use.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/instructions-for-use.md"
      }
    ]
  },
  {
    "name": "deployment-decision-record",
    "kind": "schema",
    "title": "Deployment decision record",
    "description": "The deployer's decision to put one AI system into use in one context, with the deployer duties checked one by one: use per the instructions, assigned and trained oversight, input data, monitoring, log retention, worker and affected-person information, impact assessments and registration.",
    "stage": "release",
    "stageLabel": "Release and deploy",
    "layers": [
      2,
      4
    ],
    "patterns": [
      "pattern-vendor--model-due-diligence-gate",
      "pattern-human-in-the-loop-gate",
      "pattern-decision-notice--contest-path",
      "pattern-disclosure--notification-pipeline"
    ],
    "evidences": [
      "EU AI Act Art. 26",
      "EU AI Act Art. 27",
      "EU AI Act Art. 25",
      "EU AI Act Art. 50",
      "GDPR Art. 35",
      "ISO/IEC 42001 A.9",
      "NIST AI RMF MANAGE 1.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/deployment-decision-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/deployment-decision-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/deployment-decision-record.md"
      }
    ]
  },
  {
    "name": "post-market-monitoring-plan",
    "kind": "schema",
    "title": "Post-market monitoring plan",
    "description": "How a provider watches a system after release: the data it collects, the metrics and thresholds, the triggers and the actions they fire, and how findings feed incidents, risk and retraining. Part of the technical documentation for a high-risk system.",
    "stage": "operate",
    "stageLabel": "Operate and monitor",
    "layers": [
      5
    ],
    "patterns": [
      "pattern-continuous-assurance-telemetry",
      "pattern-incident-pipeline",
      "pattern-drift--fairness-monitor"
    ],
    "evidences": [
      "EU AI Act Art. 72",
      "EU AI Act Annex IV(9)",
      "EU AI Act Art. 9(2)",
      "ISO/IEC 42001 9.1",
      "ISO/IEC 42001 A.6",
      "NIST AI RMF MANAGE 4.1",
      "NIST AI RMF MEASURE 3.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/post-market-monitoring-plan.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/post-market-monitoring-plan.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/post-market-monitoring-plan.md"
      }
    ]
  },
  {
    "name": "risk-register-entry",
    "kind": "schema",
    "title": "Risk register entry",
    "description": "One risk in the AI risk register, as code: the failure mode, its inherent and residual scores, the treatment and the controls that realise it, who accepted what remains, and the links to the incidents and eval results that keep the scores honest.",
    "stage": "operate",
    "stageLabel": "Operate and monitor",
    "layers": [
      1,
      3
    ],
    "patterns": [
      "pattern-fria-as-code",
      "pattern-continuous-assurance-telemetry"
    ],
    "evidences": [
      "EU AI Act Art. 9",
      "EU AI Act Art. 9(5)",
      "ISO/IEC 42001 6.1",
      "ISO/IEC 23894",
      "NIST AI RMF MAP 5.1",
      "NIST AI RMF MANAGE 1.2",
      "NIST AI RMF MANAGE 1.3",
      "NIST AI RMF MANAGE 1.4"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/risk-register-entry.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/risk-register-entry.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/risk-register-entry.md"
      }
    ]
  },
  {
    "name": "incident-record",
    "kind": "schema",
    "title": "AI incident record",
    "description": "One AI incident or hazard, from detection to closure. Field names follow the Commission reporting template for serious incidents involving general-purpose AI models with systemic risk and the OECD common reporting framework for AI incidents (see x-aligns-with on each field), so a report can be generated from the record rather than retyped. Adds the internal fields the pipeline needs: reporting clocks, containment, root cause and links.",
    "stage": "operate",
    "stageLabel": "Operate and monitor",
    "layers": [
      5,
      4
    ],
    "patterns": [
      "pattern-incident-pipeline",
      "pattern-kill-switch--circuit-breaker"
    ],
    "evidences": [
      "EU AI Act Art. 73",
      "EU AI Act Art. 55(1)(c)",
      "EU AI Act Art. 26(5)",
      "EU AI Act Art. 72",
      "GPAI Code of Practice, Safety and Security, Commitment 9",
      "ISO/IEC 42001 10.2",
      "NIST AI RMF MANAGE 4.3",
      "NIST AI RMF MANAGE 2.3"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/incident-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/incident-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/incident-record.md"
      }
    ]
  },
  {
    "name": "decommissioning-runbook",
    "kind": "schema",
    "title": "Decommissioning runbook",
    "description": "The executed plan for retiring one AI system or agent: why, who is told, each step with its owner and evidence (identity revoked, traffic stopped, register entry retired, evidence archived, data disposed of), and the sign-off.",
    "stage": "retire",
    "stageLabel": "Retire",
    "layers": [
      2,
      4
    ],
    "patterns": [
      "pattern-kill-switch--circuit-breaker",
      "pattern-agent-registry",
      "pattern-deactivation-localisation--retirement-runbook"
    ],
    "evidences": [
      "NIST AI RMF GOVERN 1.7",
      "NIST AI RMF MANAGE 2.4",
      "EU AI Act Art. 18",
      "EU AI Act Art. 26(6)",
      "ISO/IEC 42001 A.6",
      "GDPR Art. 5(1)(e)"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/decommissioning-runbook.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/decommissioning-runbook.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/decommissioning-runbook.md"
      }
    ]
  },
  {
    "name": "policy-card",
    "kind": "schema",
    "title": "Policy card",
    "description": "A governance rule set as a machine-readable artefact that travels with the system it governs: each rule's effect, the failure mode it addresses, where it is enforced and the engine module that implements it. Every evaluation emits a verdict in the shape published in chapter 05 ($defs/verdict).",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      1
    ],
    "patterns": [
      "pattern-policy-card",
      "pattern-framework-crosswalk"
    ],
    "evidences": [
      "EU AI Act Art. 9",
      "EU AI Act Art. 17",
      "ISO/IEC 42001 5.2",
      "ISO/IEC 42001 A.2",
      "NIST AI RMF GOVERN 1.2",
      "NIST AI RMF GOVERN 1.4"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/policy-card.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/policy-card.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/policy-card.md"
      }
    ]
  },
  {
    "name": "training-record",
    "kind": "schema",
    "title": "Training record",
    "description": "Proof that one person completed one AI literacy or role-based module, with the assessment result and the access it unlocks. Pseudonymous by design: the record carries a person reference, not a name.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      1
    ],
    "patterns": [
      "pattern-human-in-the-loop-gate",
      "pattern-agent-identity--scoped-credentials",
      "pattern-sanctioned-ai-gateway"
    ],
    "evidences": [
      "EU AI Act Art. 4",
      "EU AI Act Art. 26(2)",
      "EU AI Act Art. 14",
      "ISO/IEC 42001 7.2",
      "ISO/IEC 42001 7.3",
      "NIST AI RMF GOVERN 2.2",
      "NIST AI RMF MAP 3.4"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/training-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/training-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/training-record.md"
      }
    ]
  },
  {
    "name": "evidence-record",
    "kind": "schema",
    "title": "Evidence record",
    "description": "The common, signed record every control writes to the assurance store, as published in chapter 05: which control decided what about which subject, against which metric and obligation, on which input, when and by whom. Other records (verdicts, eval results, admissions, go/no-go) can be normalised into it on ingest.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      5
    ],
    "patterns": [
      "pattern-continuous-assurance-telemetry",
      "pattern-machine-readable-evidence-oscal",
      "pattern-model-artefact-integrity",
      "pattern-sanctioned-ai-gateway"
    ],
    "evidences": [
      "EU AI Act Art. 12",
      "EU AI Act Art. 17",
      "EU AI Act Art. 72",
      "ISO/IEC 42001 9.1",
      "NIST AI RMF MEASURE 3.1",
      "NIST AI RMF MANAGE 4.1"
    ],
    "files": [
      {
        "role": "schema",
        "format": "json",
        "path": "/schemas/evidence-record.v1.json"
      },
      {
        "role": "example",
        "format": "json",
        "path": "/schemas/examples/evidence-record.example.json"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/evidence-record.md"
      }
    ]
  },
  {
    "name": "ai-policy",
    "kind": "kit",
    "title": "AI policy (YAML, prose and Rego)",
    "description": "One YAML source for the AI policy, with the prose policy people approve and the Rego skeleton an engine evaluates, keyed to the same rule ids.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      1
    ],
    "patterns": [
      "pattern-policy-card",
      "pattern-framework-crosswalk"
    ],
    "evidences": [
      "ISO/IEC 42001 5.2",
      "ISO/IEC 42001 A.2",
      "NIST AI RMF GOVERN 1.2",
      "NIST AI RMF GOVERN 1.4",
      "EU AI Act Art. 17"
    ],
    "files": [
      {
        "role": "template",
        "format": "yaml",
        "path": "/templates/ai-policy.yaml"
      },
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/ai-policy.md"
      },
      {
        "role": "template",
        "format": "rego",
        "path": "/templates/ai-policy.rego"
      }
    ]
  },
  {
    "name": "committee-charter",
    "kind": "kit",
    "title": "AI governance committee charter",
    "description": "Authority, membership, quorum, inputs and outputs of the forum that takes the decisions the policy reserves, each decision written as a signed record.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      1
    ],
    "patterns": [
      "pattern-policy-card"
    ],
    "evidences": [
      "ISO/IEC 42001 5.3",
      "ISO/IEC 42001 A.3",
      "NIST AI RMF GOVERN 2.1",
      "NIST AI RMF GOVERN 2.3",
      "EU AI Act Art. 17"
    ],
    "files": [
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/committee-charter.md"
      }
    ]
  },
  {
    "name": "raci",
    "kind": "kit",
    "title": "Lifecycle RACI",
    "description": "Who is responsible, accountable, consulted and informed for each lifecycle activity, with the record each activity produces.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      1
    ],
    "patterns": [
      "pattern-policy-card"
    ],
    "evidences": [
      "ISO/IEC 42001 A.3",
      "NIST AI RMF GOVERN 2.1"
    ],
    "files": [
      {
        "role": "template",
        "format": "csv",
        "path": "/templates/raci.csv"
      }
    ]
  },
  {
    "name": "policy-gap-assessment",
    "kind": "kit",
    "title": "Policy gap assessment",
    "description": "A worksheet to test existing policies (privacy, security, data, IP, acceptable use, procurement, HR) against AI, with the evidence each answer needs.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      1,
      5
    ],
    "patterns": [
      "pattern-framework-crosswalk"
    ],
    "evidences": [
      "ISO/IEC 42001 A.2",
      "NIST AI RMF GOVERN 1.1"
    ],
    "files": [
      {
        "role": "template",
        "format": "csv",
        "path": "/templates/policy-gap-assessment.csv"
      }
    ]
  },
  {
    "name": "literacy-curriculum",
    "kind": "kit",
    "title": "AI literacy curriculum",
    "description": "Role-based modules with objectives, format, assessment, refresh cycle and the access each unlocks; completions are training records.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      1
    ],
    "patterns": [
      "pattern-human-in-the-loop-gate"
    ],
    "evidences": [
      "EU AI Act Art. 4",
      "ISO/IEC 42001 7.2",
      "ISO/IEC 42001 7.3",
      "NIST AI RMF GOVERN 2.2"
    ],
    "files": [
      {
        "role": "template",
        "format": "csv",
        "path": "/templates/literacy-curriculum.csv"
      }
    ]
  },
  {
    "name": "contract-clause-checklist",
    "kind": "kit",
    "title": "AI contract clause checklist",
    "description": "The terms an AI supply contract should settle, each tied to its obligation and to the due-diligence field it closes. What to secure, not clause wording.",
    "stage": "organisation",
    "stageLabel": "Organisation-wide",
    "layers": [
      2,
      5
    ],
    "patterns": [
      "pattern-vendor--model-due-diligence-gate"
    ],
    "evidences": [
      "EU AI Act Art. 25",
      "GDPR Art. 28",
      "ISO/IEC 42001 A.10",
      "NIST AI RMF GOVERN 6.1"
    ],
    "files": [
      {
        "role": "template",
        "format": "markdown",
        "path": "/templates/contract-clause-checklist.md"
      }
    ]
  }
];
